### ISSUE TITLE
Polkadot indexed data

### ISSUE THREAD

**Issue by kevin-hermeneutic** [metaspan/metaspan.io#44]
Hello dcolley, I was wondering if you have indexed data polka-store for polkadot chain from genesis block(0th) to the current block(17.2million blocks)?

I am trying to get all polkadot data from genesis block(0th to the current block(~17.2million blocks)) but from other sources would take weeks.

I need all events/types of transactions data and balances relevant transactions, thank you!

**Comment by dcolley** [comment]
Using polkascan it does take ages. We do not have the full set yet...!
Have you tried subsquid or subscan API?

**Comment by kevin-hermeneutic** [comment]
subsquid has no python api it is javascript

**Comment by kevin-hermeneutic** [comment]
also subscan only

5 Req/SUp to 1 API key100,000 Req/d
